### PR TITLE
feature: Install remove instances

### PR DESCRIPTION
**Pull request by CODeRUS**
Huge PR with tons of changes. Mostly around implementing installing/removing instances on the fly without full reinstall. WIth some other bugs fixed on the go. Probably some new bugs introduces, requires good review.

~~For now I'd continue to work on streamer installation refactor with same technique used.~~

EDIT: @KwadFan will implement crownest installation

### CODE REVIEW

**Comment by th33xitus** [comment]
Hit thanks a lot for this PR, i will have a look at it. That feature was on my todo list for a long time, i just haven't had time to start it myself.

For the streamer installation, please make a separate PR. Im likely going to push a commit today which will hide the install option from the install menu temporarily. Too many "bug-reports" from people not understanding the meaning of the "function currently disabled" message.

**Comment by KwadFan** [comment]
@CODeRUS If you are ok with it I would do an PR containing Crowsnest install. I dont know if it would be useful to fix outdated mjpeg streamer, but imho not.

**Comment by CODeRUS** [comment]
@th33xitus okay for streamer. For same technique i meant: choose klipper instance to determine "printer_data" folder to put streamer config to, then ask for name.

**Comment by CODeRUS** [comment]
@KwadFan crownest should be easy, it contains own installation scripts asking users for details

**Comment by CODeRUS** [comment]
okay then, just waiting for reviews :)

**Comment by KwadFan** [comment]
> @KwadFan crownest should be easy, it contains own installation scripts asking users for details
> 

I think so, especially for me, I am the creator of ;)

The question was more or less, will you skip that step then? Dont want to do work twice or better said mafe by different peops...

**Comment by CODeRUS** [comment]
@KwadFan sure, go ahead, it would be good if you can implement it for kiauh.

**Comment by KwadFan** [comment]
Great, for sure will do during this week.

**Comment by th33xitus** [comment]
@CODeRUS sorry that i still haven't reviewed. Im currently in the process of moving house to a different city, so i have very very little time currently, i hope i will find some time during the next weeks. i hope thats okay. just wanted to let you know that i havent forgot about this PR.

**Comment by randallknutson** [comment]
I tested this out and it appeared to work. The interface confused me at first but I figured it out. I had two instances installed from my original install and wanted to add two more. The sequence that worked was to go to Klipper install and put 4. Then enter the same names as the original instances and allow it to warn that they already exist. Then enter the two new names and it installed Klipper for all 4 instances. Next I went to moonraker install and it showed the Klipper instances that wasn't installed for and I was able to install for them. Even though it was a little confusing I'm happy I was able to do this without starting over.

**Comment by CODeRUS** [comment]
@randallknutson thanks for testing! I agree this may require some nice touches by maintainer itself to ake it ore clear for user and better fit to existing design.

**Comment by CODeRUS** [comment]
@th33xitus fyi: updated to master, with fixing couple small things i spotted

**Comment by th33xitus** [comment]
@CODeRUS thank you, but in case you find more such things, please don't push them into this PR and make new ones if they can be applied standalone to master. lets keep this PR only for the requested feature, that will make things much easier.

im going to start pushing to this PR as well from now on to finally start and get this feature in. hope you are okay with this.

**Comment by CODeRUS** [comment]
@th33xitus yes sure, as soon as it helps landing this feature into master, i'm totally for it!

**Comment by dw-0** [comment]
This is possible with KIAUH v6 which's alpha got released just a minute ago. So im closing this PR for now. Thanks anyways!

**Pull request closed without merging**
